-- Algeria Travel — contenu du site (circuits, activités, hébergements, blog, destinations)

-- ─── Destinations / places ──────────────────────────────────────────────────
create table if not exists public.places (
  id              text primary key,
  name            text not null,
  name_en         text,
  name_ar         text,
  tagline         text,
  tagline_en      text,
  tagline_ar      text,
  rating          numeric(2,1) default 4.5,
  reviews         integer default 0,
  temp            text,
  image           text,
  gallery         jsonb default '[]'::jsonb,
  description     text,
  description_en  text,
  description_ar  text,
  best_time       text,
  best_time_en    text,
  best_time_ar    text,
  duration        text,
  duration_en     text,
  duration_ar     text,
  price           integer,
  old_price       integer,
  stay            text,
  stay_en         text,
  stay_ar         text,
  transport       text,
  transport_en    text,
  transport_ar    text,
  includes        jsonb default '[]'::jsonb,
  highlights      jsonb default '[]'::jsonb,
  published       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─── Circuits / tours ───────────────────────────────────────────────────────
create table if not exists public.tours (
  id              bigint generated by default as identity primary key,
  name            text not null,
  name_en         text,
  name_ar         text,
  subtitle        text,
  subtitle_en     text,
  subtitle_ar     text,
  description     text,
  description_en  text,
  full_description text,
  full_description_en text,
  location        text,
  location_en     text,
  location_ar     text,
  best_time       text,
  best_time_en    text,
  best_time_ar    text,
  duration        text,
  duration_en     text,
  duration_ar     text,
  price           integer,
  old_price       integer,
  rating          numeric(2,1) default 4.5,
  reviews         integer default 0,
  image           text,
  category        text,
  activities      jsonb default '[]'::jsonb,
  itinerary       jsonb default '[]'::jsonb,
  place_slug      text,
  pkg             text,
  badge           text,
  published       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─── Activités ──────────────────────────────────────────────────────────────
create table if not exists public.activities (
  id              text primary key,
  name            text not null,
  name_en         text,
  name_ar         text,
  "desc"          text,
  desc_en         text,
  desc_ar         text,
  full_desc       text,
  full_desc_en    text,
  full_desc_ar    text,
  history         text,
  history_en      text,
  history_ar      text,
  visit           text,
  visit_en        text,
  visit_ar        text,
  icon            text,
  color           text,
  category        text,
  filters         jsonb default '[]'::jsonb,
  places          jsonb default '[]'::jsonb,
  tags            jsonb default '{}'::jsonb,
  duration_short  text,
  duration_short_en text,
  duration_short_ar text,
  image           text,
  gallery         jsonb default '[]'::jsonb,
  price           integer,
  duration        text,
  duration_en     text,
  duration_ar     text,
  location        text,
  location_en     text,
  location_ar     text,
  dates           text,
  dates_en        text,
  dates_ar        text,
  "group"         text,
  group_en        text,
  group_ar        text,
  rating          numeric(2,1) default 4.5,
  included        jsonb default '[]'::jsonb,
  included_en     jsonb default '[]'::jsonb,
  included_ar     jsonb default '[]'::jsonb,
  published       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─── Hébergements ───────────────────────────────────────────────────────────
create table if not exists public.stays (
  id              text primary key,
  type            text not null check (type in ('hotel', 'guesthouse')),
  place_id        text,
  name            text not null,
  name_en         text,
  name_ar         text,
  location        text,
  location_en     text,
  location_ar     text,
  "desc"          text,
  desc_en         text,
  desc_ar         text,
  image           text,
  gallery         jsonb default '[]'::jsonb,
  price           integer,
  price_per_person boolean default false,
  rating          numeric(2,1) default 4.5,
  reviews         integer default 0,
  amenities       jsonb default '{}'::jsonb,
  published       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─── Blog ───────────────────────────────────────────────────────────────────
create table if not exists public.blog_posts (
  id              bigint generated by default as identity primary key,
  slug            text unique not null,
  title           text not null,
  title_en        text,
  title_ar        text,
  excerpt         text,
  excerpt_en      text,
  excerpt_ar      text,
  body            text,
  body_en         text,
  body_ar         text,
  category        text,
  category_label  text,
  category_label_en text,
  category_label_ar text,
  published_at    text,
  published_at_en text,
  published_at_ar text,
  read_time       text,
  image           text,
  featured        boolean default false,
  published       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─── Triggers updated_at ────────────────────────────────────────────────────
create or replace function public.touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
declare
  t text;
begin
  foreach t in array array['places','tours','activities','stays','blog_posts']
  loop
    execute format('drop trigger if exists trg_%s_updated on public.%s', t, t);
    execute format(
      'create trigger trg_%s_updated before update on public.%s for each row execute function public.touch_updated_at()',
      t, t
    );
  end loop;
end $$;

create index if not exists idx_tours_published on public.tours (published);
create index if not exists idx_activities_category on public.activities (category);
create index if not exists idx_stays_type on public.stays (type);
create index if not exists idx_stays_place_id on public.stays (place_id);
create index if not exists idx_blog_posts_slug on public.blog_posts (slug);
create index if not exists idx_places_published on public.places (published);
