export const ENTITIES = {
  places: {
    title: 'Destinations',
    subtitle: 'Fiches destinations du site',
    resource: 'places',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'id', label: 'ID' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  tours: {
    title: 'Circuits',
    subtitle: 'Circuits et voyages organisés',
    resource: 'tours',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'location', label: 'Lieu' },
      { key: 'duration', label: 'Durée' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  activities: {
    title: 'Activités',
    subtitle: 'Quad, trek, kayak…',
    resource: 'activities',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'id', label: 'Slug' },
      { key: 'category', label: 'Catégorie' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  stays: {
    title: 'Hébergements',
    subtitle: 'Hôtels et maisons d\'hôtes',
    resource: 'stays',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'type', label: 'Type' },
      { key: 'placeId', label: 'Destination' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  blog: {
    title: 'Blog',
    subtitle: 'Articles et actualités',
    resource: 'blog',
    idField: 'id',
    columns: [
      { key: 'title', label: 'Titre' },
      { key: 'slug', label: 'Slug' },
      { key: 'category', label: 'Catégorie' },
      { key: 'publishedAt', label: 'Date' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
};

export const FORM_CONFIGS = {
  places: {
    resource: 'places',
    title: 'Destination',
    sections: [
      {
        title: 'Identité',
        fields: [
          { name: 'id', label: 'ID (slug)', required: true, full: true, hint: 'ex: bejaia, djanet' },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'tagline', label: 'Accroche (FR)' },
          { name: 'taglineEn', label: 'Accroche (EN)' },
          { name: 'taglineAr', label: 'Accroche (AR)' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'description', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'descriptionEn', label: 'Description (EN)', type: 'textarea', full: true },
          { name: 'descriptionAr', label: 'Description (AR)', type: 'textarea', full: true },
          { name: 'bestTime', label: 'Meilleure période (FR)' },
          { name: 'duration', label: 'Durée (FR)' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'oldPrice', label: 'Ancien prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Avis', type: 'number' },
          { name: 'temp', label: 'Température affichée' },
        ],
      },
      {
        title: 'Médias & JSON',
        fields: [
          { name: 'image', label: 'Image principale', full: true },
          { name: 'gallery', label: 'Galerie (JSON array)', type: 'json', full: true },
          { name: 'includes', label: 'Inclus (JSON)', type: 'json', full: true },
          { name: 'highlights', label: 'Points forts (JSON)', type: 'json', full: true },
          { name: 'stay', label: 'Hébergement suggéré (FR)' },
          { name: 'transport', label: 'Transport (FR)', full: true },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
    ],
  },
  tours: {
    resource: 'tours',
    title: 'Circuit',
    sections: [
      {
        title: 'Informations',
        fields: [
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'subtitle', label: 'Sous-titre (FR)' },
          { name: 'location', label: 'Lieu (FR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'duration', label: 'Durée (FR)' },
          { name: 'bestTime', label: 'Meilleure période (FR)' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'oldPrice', label: 'Ancien prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Nb avis', type: 'number' },
          { name: 'placeSlug', label: 'Slug destination liée' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Descriptions',
        fields: [
          { name: 'description', label: 'Description courte (FR)', type: 'textarea', full: true },
          { name: 'descriptionEn', label: 'Description courte (EN)', type: 'textarea', full: true },
          { name: 'fullDescription', label: 'Description complète (FR)', type: 'textarea', full: true },
          { name: 'fullDescriptionEn', label: 'Description complète (EN)', type: 'textarea', full: true },
          { name: 'image', label: 'Image', full: true },
          { name: 'activities', label: 'Activités (JSON)', type: 'json', full: true },
          { name: 'itinerary', label: 'Itinéraire (JSON)', type: 'json', full: true },
        ],
      },
    ],
  },
  activities: {
    resource: 'activities',
    title: 'Activité',
    sections: [
      {
        title: 'Identité',
        fields: [
          { name: 'id', label: 'Slug', required: true, full: true },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'icon', label: 'Icône Lucide' },
          { name: 'color', label: 'Couleur hex' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'desc', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'fullDesc', label: 'Description longue (FR)', type: 'textarea', full: true },
          { name: 'history', label: 'Histoire (FR)', type: 'textarea', full: true },
          { name: 'visit', label: 'Visite (FR)', type: 'textarea', full: true },
          { name: 'durationShort', label: 'Durée courte' },
          { name: 'location', label: 'Lieux (FR)' },
          { name: 'image', label: 'Image', full: true },
          { name: 'gallery', label: 'Galerie (JSON)', type: 'json', full: true },
          { name: 'filters', label: 'Filtres (JSON array)', type: 'json', full: true },
          { name: 'places', label: 'Destinations liées (JSON array)', type: 'json', full: true },
          { name: 'tags', label: 'Tags (JSON)', type: 'json', full: true },
          { name: 'included', label: 'Inclus (JSON)', type: 'json', full: true },
        ],
      },
    ],
  },
  stays: {
    resource: 'stays',
    title: 'Hébergement',
    sections: [
      {
        title: 'Informations',
        fields: [
          { name: 'id', label: 'ID (slug)', required: true, full: true },
          { name: 'type', label: 'Type', type: 'select', options: ['hotel', 'guesthouse'] },
          { name: 'placeId', label: 'Destination (slug)' },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'location', label: 'Lieu (FR)' },
          { name: 'price', label: 'Prix/nuit (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Nb avis', type: 'number' },
          { name: 'pricePerPerson', label: 'Prix par personne', type: 'checkbox' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Description & médias',
        fields: [
          { name: 'desc', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'descEn', label: 'Description (EN)', type: 'textarea', full: true },
          { name: 'image', label: 'Image', full: true },
          { name: 'gallery', label: 'Galerie (JSON)', type: 'json', full: true },
          { name: 'amenities', label: 'Équipements (JSON {fr,en,ar})', type: 'json', full: true },
        ],
      },
    ],
  },
  blog: {
    resource: 'blog',
    title: 'Article',
    sections: [
      {
        title: 'Article',
        fields: [
          { name: 'slug', label: 'Slug URL', required: true, full: true },
          { name: 'title', label: 'Titre (FR)', required: true },
          { name: 'titleEn', label: 'Titre (EN)' },
          { name: 'titleAr', label: 'Titre (AR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'categoryLabel', label: 'Label catégorie (FR)' },
          { name: 'publishedAt', label: 'Date affichée (FR)' },
          { name: 'readTime', label: 'Temps de lecture' },
          { name: 'image', label: 'Image', full: true },
          { name: 'featured', label: 'À la une', type: 'checkbox' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'excerpt', label: 'Extrait (FR)', type: 'textarea', full: true },
          { name: 'excerptEn', label: 'Extrait (EN)', type: 'textarea', full: true },
          { name: 'body', label: 'Corps (FR)', type: 'textarea', full: true },
          { name: 'bodyEn', label: 'Corps (EN)', type: 'textarea', full: true },
        ],
      },
    ],
  },
};
