export const WILAYA_OPTIONS = [
  { code: '06', key: 'bejaia', label: '06 — Béjaïa' },
  { code: '16', key: 'alger', label: '16 — Alger' },
  { code: '31', key: 'oran', label: '31 — Oran' },
  { code: '25', key: 'constantine', label: '25 — Constantine' },
  { code: '23', key: 'annaba', label: '23 — Annaba' },
  { code: '47', key: 'ghardaia', label: '47 — Ghardaïa' },
  { code: '11', key: 'tamanrasset', label: '11 — Tamanrasset' },
  { code: '33', key: 'illizi', label: '33 — Illizi' },
  { code: '08', key: 'bechar', label: '08 — Béchar' },
  { code: '49', key: 'timimoun', label: '49 — Timimoun' },
  { code: '07', key: 'biskra', label: '07 — Biskra' },
];

const AVAILABILITY_OPTIONS = ['available', 'limited', 'unavailable'];

export const ENTITIES = {
  places: {
    title: 'Destinations',
    subtitle: 'Fiches destinations du site',
    resource: 'places',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'id', label: 'ID' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  tours: {
    title: 'Circuits',
    subtitle: 'Circuits et voyages organisés',
    resource: 'tours',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'location', label: 'Lieu' },
      { key: 'duration', label: 'Durée' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  activities: {
    title: 'Activités',
    subtitle: 'Quad, trek, kayak…',
    resource: 'activities',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'id', label: 'Slug' },
      { key: 'category', label: 'Catégorie' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  stays: {
    title: 'Hébergements',
    subtitle: 'Hôtels et maisons d\'hôtes',
    resource: 'stays',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'type', label: 'Type' },
      { key: 'placeId', label: 'Destination' },
      { key: 'price', label: 'Prix (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  hotels: {
    title: 'Hôtels',
    subtitle: 'Hôtels par wilaya — page /hotels',
    resource: 'hotels',
    idField: 'id',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'wilayaKey', label: 'Wilaya' },
      { key: 'stars', label: 'Étoiles', render: (r) => (r.stars ? `${r.stars}★` : '—') },
      { key: 'price', label: 'Prix/nuit (DA)', render: (r) => r.price?.toLocaleString?.() || '—' },
      {
        key: 'availability',
        label: 'Dispo.',
        render: (r) =>
          ({ available: 'Disponible', limited: 'Limité', unavailable: 'Complet' }[r.availability] ||
            r.availability ||
            '—'),
      },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  blog: {
    title: 'Blog',
    subtitle: 'Articles et actualités',
    resource: 'blog',
    idField: 'id',
    columns: [
      { key: 'title', label: 'Titre' },
      { key: 'slug', label: 'Slug' },
      { key: 'category', label: 'Catégorie' },
      { key: 'publishedAt', label: 'Date' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
  gallery: {
    title: 'Galerie',
    subtitle: 'Photos publiques du site',
    resource: 'gallery',
    idField: 'id',
    columns: [
      { key: 'captionFr', label: 'Légende' },
      { key: 'src', label: 'Image' },
      { key: 'sortOrder', label: 'Ordre' },
      { key: 'published', label: 'Statut', render: (r) => (r.published ? 'Publié' : 'Brouillon') },
    ],
  },
};

export const FORM_CONFIGS = {
  places: {
    resource: 'places',
    title: 'Destination',
    sections: [
      {
        title: 'Identité',
        fields: [
          { name: 'id', label: 'ID (slug)', required: true, full: true, hint: 'ex: bejaia, djanet' },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'tagline', label: 'Accroche (FR)' },
          { name: 'taglineEn', label: 'Accroche (EN)' },
          { name: 'taglineAr', label: 'Accroche (AR)' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'description', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'descriptionEn', label: 'Description (EN)', type: 'textarea', full: true },
          { name: 'descriptionAr', label: 'Description (AR)', type: 'textarea', full: true },
          { name: 'bestTime', label: 'Meilleure période (FR)' },
          { name: 'duration', label: 'Durée (FR)' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'oldPrice', label: 'Ancien prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Avis', type: 'number' },
          { name: 'temp', label: 'Température affichée' },
        ],
      },
      {
        title: 'Médias & JSON',
        fields: [
          { name: 'image', label: 'Image principale', type: 'image', full: true },
          { name: 'gallery', label: 'Galerie photos', type: 'gallery', full: true },
          { name: 'includes', label: 'Inclus (JSON)', type: 'json', full: true },
          { name: 'highlights', label: 'Points forts (JSON)', type: 'json', full: true },
          { name: 'stay', label: 'Hébergement suggéré (FR)' },
          { name: 'transport', label: 'Transport (FR)', full: true },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
    ],
  },
  tours: {
    resource: 'tours',
    title: 'Circuit',
    sections: [
      {
        title: 'Informations',
        fields: [
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'subtitle', label: 'Sous-titre (FR)' },
          { name: 'location', label: 'Lieu (FR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'duration', label: 'Durée (FR)' },
          { name: 'bestTime', label: 'Meilleure période (FR)' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'oldPrice', label: 'Ancien prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Nb avis', type: 'number' },
          { name: 'placeSlug', label: 'Slug destination liée' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Descriptions',
        fields: [
          { name: 'description', label: 'Description courte (FR)', type: 'textarea', full: true },
          { name: 'descriptionEn', label: 'Description courte (EN)', type: 'textarea', full: true },
          { name: 'fullDescription', label: 'Description complète (FR)', type: 'textarea', full: true },
          { name: 'fullDescriptionEn', label: 'Description complète (EN)', type: 'textarea', full: true },
          { name: 'image', label: 'Image', type: 'image', full: true },
          { name: 'activities', label: 'Activités (JSON)', type: 'json', full: true },
          { name: 'itinerary', label: 'Itinéraire (JSON)', type: 'json', full: true },
        ],
      },
    ],
  },
  activities: {
    resource: 'activities',
    title: 'Activité',
    sections: [
      {
        title: 'Identité',
        fields: [
          { name: 'id', label: 'Slug', required: true, full: true },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'icon', label: 'Icône Lucide' },
          { name: 'color', label: 'Couleur hex' },
          { name: 'price', label: 'Prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'desc', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'fullDesc', label: 'Description longue (FR)', type: 'textarea', full: true },
          { name: 'history', label: 'Histoire (FR)', type: 'textarea', full: true },
          { name: 'visit', label: 'Visite (FR)', type: 'textarea', full: true },
          { name: 'durationShort', label: 'Durée courte' },
          { name: 'location', label: 'Lieux (FR)' },
          { name: 'image', label: 'Image', type: 'image', full: true },
          { name: 'gallery', label: 'Galerie photos', type: 'gallery', full: true },
          { name: 'filters', label: 'Filtres (JSON array)', type: 'json', full: true },
          { name: 'places', label: 'Destinations liées (JSON array)', type: 'json', full: true },
          { name: 'tags', label: 'Tags (JSON)', type: 'json', full: true },
          { name: 'included', label: 'Inclus (JSON)', type: 'json', full: true },
        ],
      },
    ],
  },
  stays: {
    resource: 'stays',
    title: 'Hébergement',
    sections: [
      {
        title: 'Informations',
        fields: [
          { name: 'id', label: 'ID (slug)', required: true, full: true },
          { name: 'type', label: 'Type', type: 'select', options: ['hotel', 'guesthouse'] },
          { name: 'placeId', label: 'Destination (slug)' },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'location', label: 'Lieu (FR)' },
          { name: 'price', label: 'Prix/nuit (DA)', type: 'number' },
          { name: 'rating', label: 'Note', type: 'number' },
          { name: 'reviews', label: 'Nb avis', type: 'number' },
          { name: 'pricePerPerson', label: 'Prix par personne', type: 'checkbox' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Description & médias',
        fields: [
          { name: 'desc', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'descEn', label: 'Description (EN)', type: 'textarea', full: true },
          { name: 'image', label: 'Image', type: 'image', full: true },
          { name: 'gallery', label: 'Galerie photos', type: 'gallery', full: true },
          { name: 'amenities', label: 'Équipements (JSON {fr,en,ar})', type: 'json', full: true },
        ],
      },
    ],
  },
  hotels: {
    resource: 'hotels',
    title: 'Hôtel',
    sections: [
      {
        title: 'Identité & wilaya',
        fields: [
          { name: 'id', label: 'ID (slug URL)', required: true, full: true, hint: 'ex: hotel-royal-bejaia' },
          {
            name: 'wilayaKey',
            label: 'Wilaya',
            type: 'select',
            required: true,
            options: WILAYA_OPTIONS.map((w) => w.key),
            optionLabels: Object.fromEntries(WILAYA_OPTIONS.map((w) => [w.key, w.label])),
          },
          { name: 'wilaya', label: 'Code wilaya', hint: 'ex: 06 (rempli auto si possible)' },
          { name: 'name', label: 'Nom (FR)', required: true },
          { name: 'nameEn', label: 'Nom (EN)' },
          { name: 'nameAr', label: 'Nom (AR)' },
          { name: 'stars', label: 'Étoiles (1-5)', type: 'number' },
          {
            name: 'availability',
            label: 'Disponibilité',
            type: 'select',
            options: AVAILABILITY_OPTIONS,
            optionLabels: {
              available: 'Disponible',
              limited: 'Places limitées',
              unavailable: 'Complet',
            },
          },
          { name: 'roomsAvailable', label: 'Chambres disponibles', type: 'number' },
          { name: 'published', label: 'Publié sur le site', type: 'checkbox' },
        ],
      },
      {
        title: 'Tarifs & avis',
        fields: [
          { name: 'price', label: 'Prix/nuit (DA)', type: 'number', required: true },
          { name: 'oldPrice', label: 'Ancien prix (DA)', type: 'number' },
          { name: 'rating', label: 'Note (0-5)', type: 'number' },
          { name: 'reviews', label: 'Nb avis', type: 'number' },
          { name: 'checkIn', label: 'Heure arrivée', hint: 'ex: 14:00' },
          { name: 'checkOut', label: 'Heure départ', hint: 'ex: 12:00' },
        ],
      },
      {
        title: 'Localisation',
        fields: [
          { name: 'location', label: 'Ville affichée (FR)' },
          { name: 'locationEn', label: 'Ville (EN)' },
          { name: 'locationAr', label: 'Ville (AR)' },
          { name: 'address', label: 'Adresse (FR)', full: true },
          { name: 'addressEn', label: 'Adresse (EN)', full: true },
          { name: 'addressAr', label: 'Adresse (AR)', full: true },
          { name: 'phone', label: 'Téléphone' },
          { name: 'lat', label: 'Latitude', type: 'number' },
          { name: 'lng', label: 'Longitude', type: 'number' },
          { name: 'placeId', label: 'Slug destination liée (optionnel)' },
        ],
      },
      {
        title: 'Description & médias',
        fields: [
          { name: 'desc', label: 'Description (FR)', type: 'textarea', full: true },
          { name: 'descEn', label: 'Description (EN)', type: 'textarea', full: true },
          { name: 'descAr', label: 'Description (AR)', type: 'textarea', full: true },
          { name: 'image', label: 'Photo principale', type: 'image', full: true },
          { name: 'gallery', label: 'Galerie photos', type: 'gallery', full: true },
          {
            name: 'amenities',
            label: 'Équipements (JSON {fr,en,ar})',
            type: 'json',
            full: true,
            hint: '{"fr":["Wifi","Piscine"],"en":["Wifi","Pool"],"ar":["واي فاي","مسبح"]}',
          },
        ],
      },
    ],
  },
  blog: {
    resource: 'blog',
    title: 'Article',
    sections: [
      {
        title: 'Article',
        fields: [
          { name: 'slug', label: 'Slug URL', required: true, full: true },
          { name: 'title', label: 'Titre (FR)', required: true },
          { name: 'titleEn', label: 'Titre (EN)' },
          { name: 'titleAr', label: 'Titre (AR)' },
          { name: 'category', label: 'Catégorie' },
          { name: 'categoryLabel', label: 'Label catégorie (FR)' },
          { name: 'publishedAt', label: 'Date affichée (FR)' },
          { name: 'readTime', label: 'Temps de lecture' },
          { name: 'image', label: 'Image', type: 'image', full: true },
          { name: 'featured', label: 'À la une', type: 'checkbox' },
          { name: 'published', label: 'Publié', type: 'checkbox' },
        ],
      },
      {
        title: 'Contenu',
        fields: [
          { name: 'excerpt', label: 'Extrait (FR)', type: 'textarea', full: true },
          { name: 'excerptEn', label: 'Extrait (EN)', type: 'textarea', full: true },
          { name: 'body', label: 'Corps (FR)', type: 'textarea', full: true },
          { name: 'bodyEn', label: 'Corps (EN)', type: 'textarea', full: true },
        ],
      },
    ],
  },
  gallery: {
    resource: 'gallery',
    title: 'Photo galerie',
    sections: [
      {
        title: 'Photo',
        fields: [
          { name: 'src', label: 'Photo', type: 'image', required: true, full: true },
          { name: 'alt', label: 'Texte alternatif' },
          { name: 'captionFr', label: 'Légende (FR)' },
          { name: 'captionEn', label: 'Légende (EN)' },
          { name: 'captionAr', label: 'Légende (AR)' },
          { name: 'sortOrder', label: 'Ordre d\'affichage', type: 'number' },
          { name: 'published', label: 'Publié (notifie les abonnés)', type: 'checkbox' },
        ],
      },
    ],
  },
};
